#!/bin/sh

# reload-varnish: Script to reload varnishd from VCL defined in
# /etc/sysconfig/varnish.
#
# Stig Sandbeck Mathisen <ssm@debian.org>
# Elan Ruusamäe <glen@pld-linux.org>

if [ -z "$INIT_COL" ]; then
	# if invoked directly, load rc-scripts functions
	. /etc/rc.d/init.d/functions
fi

# Settings
defaults=/etc/sysconfig/varnish

# Paths
varnishadm=/usr/bin/varnishadm
date=/bin/date
mktemp=/bin/mktemp

# Generate a label, prefixed with the caller's username, from the
# kernel random uuid generator, fallback to timestamp
if [ -f /proc/sys/kernel/random/uuid ]; then
	read uuid < /proc/sys/kernel/random/uuid
	vcl_label="${LOGNAME}${LOGNAME:+:}${uuid}"
else
	vcl_label="$($date +${LOGNAME}${LOGNAME:+:}%s.%N)"
fi

# Load defaults file
if [ -f "$defaults" ]; then
	if [ -r "$defaults" ]; then
		. "$defaults"
	else
		nls "Error: %s is not readable\n" $defaults
		exit 1
	fi
else
	nls "Error: %s does not exist\n" $defaults
	exit 1
fi

# parse command line arguments
while getopts hcq flag; do
	case $flag in
	h)
		nls "Usage: $0 [-h][-c][-q]\n\t-h\tdisplay help\n\t-q\tquiet\n\t-c\tcompile only, do not reload\n"
		exit 0
		;;
	c)
		compile_only=1
		;;
	q)
		quiet=1
		;;
	*)
		nls "Usage: $0 [-h][-c][-q]\n\t-h\tdisplay help\n\t-q\tquiet\n\t-c\tcompile only, do not reload\n"
		exit 1
		;;
	esac
done

vcl_file=${VARNISH_VCL_CONF}
mgmt_interface=${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT}

# Parse $DAEMON_OPTS (options must be kept in sync with varnishd).
# Extract the -f and the -T option, and (try to) ensure that the
# management interface is on the form hostname:address
OPTIND=1
while getopts a:b:dFf:g:h:l:n:P:p:s:T:t:u:Vw: flag $DAEMON_OPTS; do
	case $flag in
	f)
		if [ -f "$OPTARG" ]; then
		vcl_file="$OPTARG"
		fi
		;;
	T)
		if [ -n "$OPTARG" -a "$OPTARG" != "${OPTARG%%:*}" ]
		then
		mgmt_interface="$OPTARG"
		fi
		;;
	esac
done

# Sanity checks
if [ ! -x "$varnishadm" ]; then
	nls "Error: Cannot execute %s\n" $varnishadm
    exit 1
fi

if [ -z "$mgmt_interface" ]; then
	nls "Error: \$DAEMON_OPTS must contain '-T hostname:port'\n"
    exit 1
fi

if [ -z "$vcl_file" ]; then
	nls "Error: No VCL file used, nothing to reload\n"
    exit 1
fi

logfile=$($mktemp -t $vcl_labelXXXXXX)

# Compile and maybe reload
if $varnishadm -T $mgmt_interface vcl.load $vcl_label $vcl_file; then
	if [ -n "$compile_only" ]; then
		nls "To activate, run:\n\t%s -T %s \\\\\n\tvcl.use %s\n" $varnishadm $mgmt_interface $vcl_label
	else
		if $varnishadm -T $mgmt_interface vcl.use $vcl_label; then
			nls "VCL reloaded, active label is %s\n" $vcl_label
		else
			nls "Error: vcl.use %s failed\n" $vcl_label
			exitstatus=1
		fi
	fi
else
	nls "Error: vcl.load %s %s failed" $vcl_label $vcl_file
	exitstatus=1
fi | grep -v "^$" > $logfile

# Blather
if [ -z "${quiet}" -o -n "$exitstatus" ]; then
	cat >&2 $logfile
fi

# Cleanup
rm -f $logfile
exit $exitstatus
